# Generated by Django 2.1.7 on 2019-03-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190326_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoRecetaVendida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('volumen', models.IntegerField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_ingrediente', to='core.Ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_receta', to='core.Receta')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_venta', to='core.Venta')),
            ],
        ),
    ]
