# Generated by Django 2.1.7 on 2019-03-30 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_traspaso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('timestamp_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(auto_now_add=True)),
                ('timestamp_cierre', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('0', 'ABIERTA'), ('1', 'CERRADA')], default='0', max_length=1)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_almacen', to='core.Almacen')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_sucursal', to='core.Sucursal')),
                ('usuario_alta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_usuario_alta', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_usuario_cierre', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_botella', models.IntegerField(blank=True, null=True)),
                ('timestamp_inspeccion', models.DateTimeField(auto_now_add=True)),
                ('botella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_botella', to='core.Botella')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_inspeccionados', to='core.Inspeccion')),
            ],
        ),
    ]
