# Generated by Django 2.1.7 on 2019-04-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inspeccion_iteminspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botella',
            name='estado',
            field=models.CharField(choices=[('2', 'NUEVA'), ('1', 'CON LIQUIDO'), ('0', 'VACIA'), ('3', 'PERDIDA')], default='2', max_length=1),
        ),
    ]
