# Generated by Django 2.1.8 on 2019-04-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productosinregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='timestamp_cierre',
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='fecha_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='timestamp_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='iteminspeccion',
            name='timestamp_inspeccion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
