# Generated by Django 2.1.9 on 2019-07-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_botella_peso_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='tipo',
            field=models.CharField(choices=[('1', 'BARRA'), ('0', 'BODEGA')], default='1', max_length=1),
        ),
    ]
