# Generated by Django 2.1.13 on 2019-11-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191113_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosinregistro',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_sin_registro', to='core.Sucursal'),
        ),
    ]
