# Generated by Django 3.2.7 on 2021-09-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191113_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='botella',
            name='sat_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botella',
            name='folio',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='folio',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
