# Generated by Django 2.2.24 on 2021-11-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210921_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botella',
            name='folio',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='botella',
            name='sat_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
