# Generated by Django 2.1.7 on 2019-03-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_almacen_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('unidades', models.IntegerField()),
                ('importe', models.IntegerField()),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Caja')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_receta', to='core.Receta')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_sucursal', to='core.Sucursal')),
            ],
        ),
    ]
