# Generated by Django 2.1.7 on 2019-03-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_caja', to='core.Caja'),
        ),
    ]
