# Generated by Django 2.1.7 on 2019-04-14 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190406_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSinRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(blank=True, max_length=255)),
                ('codigo_pos', models.CharField(blank=True, max_length=255)),
                ('caja', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
    ]
