# Generated by Django 2.1.9 on 2019-06-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_inspeccion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='botella',
            name='peso_actual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
