# Generated by Django 2.1.9 on 2019-07-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_almacen_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MermaIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(blank=True, default=None, null=True)),
                ('fecha_final', models.DateField(blank=True, default=None, null=True)),
                ('consumo_ventas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('consumo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('merma', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas_almacen', to='core.Almacen')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas_ingrediente', to='core.Ingrediente')),
            ],
            options={
                'verbose_name_plural': 'MermasIngredientes',
            },
        ),
        migrations.CreateModel(
            name='ReporteMermas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_inicial', models.DateField(blank=True, default=None, null=True)),
                ('fecha_final', models.DateField(blank=True, default=None, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_mermas_almacen', to='core.Almacen')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_mermas_inspeccion', to='core.Inspeccion')),
            ],
            options={
                'verbose_name_plural': 'ReportesMermas',
                'get_latest_by': 'fecha_registro',
            },
        ),
        migrations.AddField(
            model_name='mermaingrediente',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mermas_reporte', to='core.ReporteMermas'),
        ),
    ]
