# Generated by Django 2.1.9 on 2019-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190704_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='botella',
            name='fecha_envasado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='botella',
            name='lote_produccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='botella',
            name='numero_pedimento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_envasado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='lote_produccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_pedimento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
