# Generated by Django 2.1.9 on 2019-10-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_producto_peso_nueva'),
    ]

    operations = [
        migrations.AddField(
            model_name='botella',
            name='peso_nueva',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
