# Generated by Django 2.1.13 on 2019-11-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191003_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosinregistro',
            name='importe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productosinregistro',
            name='unidades',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
